---
- name: backup original page icon
  command: cp -a "{{ item }}" "{{ item }}.orig"
  args:
    creates: "{{ item }}.orig"
  loop:
    - "{{ squid_etc_dir }}/errorpage.css"
    - "{{ squid_share_dir }}/icons/SN.png"
  loop_control:
    label: "{{ item |basename }}"

- name: reset error page stylesheet and icon
  copy:
    dest: "{{ item }}"
    content: ""
    force: true
  loop:
    - "{{ squid_etc_dir }}/errorpage.css"
    - "{{ squid_share_dir }}/icons/SN.png"
  loop_control:
    label: "{{ item |basename }}"
  register: reset_stylesheet_result
  notify: restart squid service

- name: stop squid service before patching the binary
  systemd:
    name: "{{ squid_pkg }}"
    state: stopped
  # assume that binary needs patching if stylesheet was patched
  when: reset_stylesheet_result is changed

- name: patch version signature in the squid binary
  # replace string "squid/3.5.x" by "nginx/1.5.x"
  # must keep replaced string length unchanged!
  replace:
    path: "/usr/sbin/{{ squid_pkg }}"
    regexp: 'squid/[1-5]([\d.]+\0)'
    replace: 'nginx/1\1'
    encoding: latin
    backup: true
    validate: 'sh -c "exe=%s && chmod +x $exe && $exe -v"'
  notify:
    - restart squid service
    - hold squid upgrades
...
