---
- name: open (or block) unencryped squid port in ferm
  ferm_port:
    port: "{{ squid_port }}"
    proto: tcp
    zone: "{{ squid_allow_plain |bool |ternary('external','internal') }}"
    solo_zone: true
    comment: squid plain
  tags:
    - skip_ansible_lint

- name: open (or block) squid ssl port in ferm
  ferm_port:
    port: "{{ squid_ssl_port }}"
    proto: tcp
    zone: external
    state: "{{ squid_ssl_enable |bool |ternary('present','absent') }}"
    comment: squid ssl
  tags:
    - skip_ansible_lint
    - srv_squid_ssl
...
