---
## OpenVZ mangles comments in /etc/hosts, and this step might report as changed
- name: add local upstream peers to /etc/hosts
  lineinfile:
    path: /etc/hosts
    regexp: '^\s*127\.0\.0\.1\s+{{ item }}(\b|$)'
    line: "127.0.0.1\t{{ item }}"
    ## docker does not allow atomic updates of /etc/hosts
    ## see https://github.com/ansible/ansible/issues/13981
    ## see https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge
    unsafe_writes: "{{ ansible_virtualization_type == 'docker' }}"
  loop: "{{ squid_domain_rules |json_query('[?!!localhost].host') }}"
...
