---
- name: add squid-ssl ppa repository
  apt_repository:
    ## (no longer maintained) https://launchpad.net/~notartom/+archive/ubuntu/squid-ssl
    ## (ok) https://launchpad.net/~llxdev/+archive/ubuntu/xenial (bionic)
    # repo: ppa:notartom/squid-ssl
    repo: "ppa:llxdev/{{ ansible_lsb.codename }}"
    codename: "{{ ansible_lsb.codename }}"
    filename: squid-ssl
    mode: 0644
    update_cache: true
  register: squid_ssl_ppa
  ## fix sporadic network failure "gpg: keyserver receive failed: Connection closed in DNS"
  until: squid_ssl_ppa is successful

- name: remove stock squid package
  apt:
    name: squid,squid3
    state: absent
    purge: true
    autoremove: true
...
