---
- name: add squid-ssl ppa repository
  apt_repository:
    # (no longer maintained) https://launchpad.net/~notartom/+archive/ubuntu/squid-ssl
    #repo: ppa:notartom/squid-ssl
    # (OK) https://launchpad.net/~llxdev/+archive/ubuntu/xenial (bionic)
    repo: "ppa:llxdev/{{ ansible_lsb.codename }}"
    codename: "{{ ansible_lsb.codename }}"
    filename: squid-ssl
  register: squid_ssl_ppa

- name: remove stock squid package
  apt:
    name:
      - squid
      - squid3
    state: absent
    purge: yes
    autoremove: yes
  when: squid_ssl_ppa is changed
        and squid_pkg == 'squid-ssl'

- name: install squid-ssl package
  apt:
    name: "{{ squid_pkg }}"
    #state: latest  # triggers galaxy warning
    state: present
    update_cache: "{{ squid_ssl_ppa is changed }}"
    install_recommends: no
...
