---
- name: install squid with ssl support
  import_tasks: install.yml
  tags: srv_squid_install


- name: setup squid ssl certificate
  import_tasks: ssl.yml
  when: squid_ssl_enable | bool
  tags: srv_squid_ssl

- name: add local upstream peers to /etc/hosts
  lineinfile:
    path: /etc/hosts
    line: "127.0.0.1\t{{ item.host }}"
    state: present
    # docker does not allow atomic updates of /etc/hosts
    # see https://github.com/ansible/ansible/issues/13981
    # see https://docs.docker.com/network/bridge/#differences-between-user-defined-bridges-and-the-default-bridge
    unsafe_writes: "{{ ansible_virtualization_type == 'docker' }}"
  loop: "{{ squid_domain_rules
          | json_query('[?!!localhost]')
          | list }}"
  loop_control:
    label: "{{ item.host }}"
  tags: srv_squid_config


- name: configure squid
  import_tasks: config.yml
  tags: srv_squid_config

- name: url-rewrite for squid
  import_tasks: url-rewrite.yml
  when: squid_url_rewrite |length > 0
  tags: srv_squid_config

- name: firewall and iptables rules for squid
  import_tasks: iptables.yml
  when: lin_use_firewall |bool


- name: stop obsolete squid service (ok to fail, if not found)
  systemd:
    name: squid
    state: stopped
    enabled: no
    daemon_reload: yes
  when: squid_pkg == 'squid-ssl'
        and squid_ssl_ppa is defined
        and squid_ssl_ppa is changed
  ignore_errors: yes
  tags: srv_squid_service

- name: activate squid-ssl service
  systemd:
    name: "{{ squid_pkg }}"
    state: started
    enabled: yes
    daemon_reload: yes
  tags: srv_squid_service


- name: directory for distributed pac files
  file:
    path: "{{ squid_etc_dir }}/pac"
    state: directory
    owner: root
    group: "{{ web_group }}"
    mode: 0750
  when: web_group is defined
  tags: srv_squid_pac

- name: generate pac files
  template:
    src: squid.pac.j2
    dest: "{{ squid_etc_dir }}/pac/{{ item.name }}.pac"
    owner: root
    group: "{{ web_group }}"
    mode: 0640
  loop: "{{ squid_pac.pac_types }}"
  loop_control:
    label: "{{ item.name }}"
  when: web_group is defined
  tags: srv_squid_pac
...
