---
- name: verify that squid ssl certificate and key are readable
  file:
    path: "{{ lecert_dir }}/{{ item }}"
    state: file
  loop: [fullchain.pem, privkey.pem]

- name: grant squid-ssl the direct access to letsencrypt cert
  ## squid-ssl v3.x from PPA is built with OpenSSL, uses split cert/key
  user:
    name: "{{ squid_user }}"
    groups: "{{ certbot_group }}"
    append: true
  notify: restart squid service
  when: squid_from_ppa |bool

- name: setup letsencrypt cert/key bundle for squid4
  ## squid v4.x is built with GnuTLS and uses cert/key bundle
  import_tasks: ssl-letsencrypt-bundle.yml
  when: not squid_from_ppa |bool
  vars:
    ssl_cert: "{{ lecert_dir }}/fullchain.pem"
    ssl_key: "{{ lecert_dir }}/privkey.pem"
    cert_update_script: /usr/local/sbin/squid-cert-update.sh
    certbot_hook_dir: /etc/letsencrypt/renewal-hooks/post
...
