---
# handlers for ivansible.srv_squid

- name: restart squid service
  systemd:
    name: "{{ squid_pkg }}"
    state: restarted
  become: true

- name: hold squid upgrades
  command: apt-mark hold "{{ squid_pkg }}"
  become: true
...
